---
- name: Main - Prepare Pi
  tags: prepare-pi
  import_tasks:
    file: prepare-pi.yml

- name: Main - Install VPN
  tags: vpn
  import_tasks:
    file: openvpn.yml

- name: Main - Install Prometheus
  tags: prometheus
  import_tasks:
    file: prometheus.yml

- name: Main - Install Node Exporter
  tags: node_exporter
  import_tasks:
    file: node_exporter.yml

- name: Main - Alertmanager
  tags: alertmanager
  import_tasks:
    file: alertmanager.yml

- name: Main - Install Grafana
  tags: Grafana
  import_tasks:
    file: grafana.yml
...
