mandatory_packages_list:
  - ufw
  - fail2ban
vpns:
  - name: saturne
    port: 51957
    proto: udp
    subnet: 10.8.0.0
    subnet_mask: 255.255.255.0
    ca: ""
    cert: ""
    key: ""
    dh: ""
    ta: ""
prometheus_archive_url: https://github.com/prometheus/prometheus/releases/download/v2.36.0/prometheus-2.36.0.linux-arm64.tar.gz
node_exporter_archive_url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-arm64.tar.gz 
