mandatory_packages_list:
  - ufw
  - fail2ban
vpns:
  - name: vpn_name
    port: 23456
    proto: udp
    subnet: 10.8.0.0
    subnet_mask: 255.255.255.0
    ca: ""
    cert: ""
    key: ""
    dh: ""
    ta: ""
telegram_receivers:
  - bot_token: "" 
    chat_id: "" 
prometheus_version: 2.36.0
node_exporter_version: 1.3.1
alertmanager_version: 0.24.0
grafana_version: 9.0.0
grafana_download_url: https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-arm64.tar.gz
prometheus_download_url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-arm64.tar.gz
node_exporter_download_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-arm64.tar.gz 
alertmanager_download_url: https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-arm64.tar.gz
